//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RejectsApp2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ConnectionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnectionSettings defaultInstance = ((ConnectionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnectionSettings())));
        
        public static ConnectionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source= \\\\\\\\\\\\\\\\svr300-003\\\\smbd\\\\Rejects DB\\\\SQLTest\\\\Backend\\\\RejectsDB-SQ" +
            "L.sqlite")]
        public string connString {
            get {
                return ((string)(this["connString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLTest\\Backend\\RejectReport.xlsx")]
        public string excelString {
            get {
                return ((string)(this["excelString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLTest\\Backend\\")]
        public string notspecexcelString {
            get {
                return ((string)(this["notspecexcelString"]));
            }
        }
    }
}
