//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RejectsApp2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ConnectionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnectionSettings defaultInstance = ((ConnectionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnectionSettings())));
        
        public static ConnectionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source= \\\\\\\\\\\\\\\\svr300-003\\\\smbd\\\\Rejects DB\\\\SQLBackend\\\\Backend\\\\RejectsDB" +
            "-SQL.sqlite")]
        public string connString {
            get {
                return ((string)(this["connString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\ScrapReport.rdlc")]
        public string scrapRepFile {
            get {
                return ((string)(this["scrapRepFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\ReceivingMRB.rdlc" +
            "")]
        public string recRepFile {
            get {
                return ((string)(this["recRepFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\OpenItems.rdlc")]
        public string openRepFile {
            get {
                return ((string)(this["openRepFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\ProductLineNon-Co" +
            "nformance.rdlc")]
        public string productRepFile {
            get {
                return ((string)(this["productRepFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\PartHistoryReport" +
            ".rdlc")]
        public string partNumRepFile {
            get {
                return ((string)(this["partNumRepFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source= \\\\\\\\\\\\\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\Backups\\EndofM" +
            "onthBackup\\EMBackupRejectsDB-SQL.sqlite")]
        public string endOfMonthBackup {
            get {
                return ((string)(this["endOfMonthBackup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source= \\\\\\\\\\\\\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\Backups\\Friday" +
            "Backup\\FBackupRejectsDB-SQL.sqlite")]
        public string fridayBackup {
            get {
                return ((string)(this["fridayBackup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\CustomReport.rdlc" +
            "")]
        public string customReportFile {
            get {
                return ((string)(this["customReportFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\GeneratedCustomRe" +
            "port.rdlc")]
        public string generatedCustomReport {
            get {
                return ((string)(this["generatedCustomReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\PrintReport.rdlc")]
        public string PrintReport {
            get {
                return ((string)(this["PrintReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source= \\\\\\\\\\\\\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\Backups\\Manual" +
            "Backup\\ManualBackupRejectsDB-SQL.sqlite")]
        public string manualBackup {
            get {
                return ((string)(this["manualBackup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\svr300-003\\smbd\\Rejects DB\\SQLBackend\\Backend\\ReportTemplates\\AllReport.rdlc")]
        public string allRepFile {
            get {
                return ((string)(this["allRepFile"]));
            }
        }
    }
}
